site_name: FDIP
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Usage: usage.md
  - Example: synth.ipynb
  # - API Reference: api_reference.md
# theme: readthedocs
plugins:
  - mkdocs-jupyter
  # - mkdocs_apidoc