site_name: FDIP
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: fdip.md
  - Example: synth.ipynb
  # - API Reference: api_reference.md
# theme:
#   name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - mknotebooks:
      execute: false
      timeout: 60
  # - mkdocs-jupyter:
  #     execute: false
  # - mkdocs_apidoc